# Generated by Django 2.1.2 on 2018-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0002_arocategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARODrugClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_acc', models.CharField(max_length=50)),
                ('dna_acc', models.CharField(max_length=50)),
                ('amr_drug_class', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AROGeneFamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_acc', models.CharField(max_length=50)),
                ('dna_acc', models.CharField(max_length=50)),
                ('amr_gene_family', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AROResistanceMechanism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_acc', models.CharField(max_length=50)),
                ('dna_acc', models.CharField(max_length=50)),
                ('amr_resistance_mechanism', models.CharField(max_length=100)),
            ],
        ),
    ]
