# Generated by Django 2.1.2 on 2018-11-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0003_arodrugclass_arogenefamily_aroresistancemechanism'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein_acc', models.CharField(max_length=50)),
                ('aro', models.CharField(max_length=30)),
                ('protein_name', models.CharField(max_length=50)),
                ('taxon_origin', models.CharField(max_length=100)),
            ],
        ),
    ]
