# Generated by Django 2.1.2 on 2018-11-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0004_proteinmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteinmodel',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='proteinmodel',
            name='sequence',
            field=models.TextField(null=True),
        ),
    ]
