# Generated by Django 2.1.2 on 2018-11-16 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0007_contiglocustoaro'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleToGeneProteinSequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locus_name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('protein_seq', models.TextField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resistome.Sample')),
            ],
        ),
    ]
