# Generated by Django 2.1.2 on 2018-11-16 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0008_sampletogeneproteinsequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sampletogeneproteinsequence',
            name='description',
            field=models.CharField(max_length=150),
        ),
    ]
