# Generated by Django 2.1.2 on 2018-11-16 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0009_auto_20181116_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContigToARO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contig_name', models.CharField(max_length=30)),
                ('aro', models.CharField(max_length=30)),
                ('pident', models.FloatField()),
                ('aln_length', models.IntegerField()),
                ('num_mismatch', models.IntegerField()),
                ('gap_open', models.IntegerField()),
                ('qstart', models.IntegerField()),
                ('qend', models.IntegerField()),
                ('aro_start', models.IntegerField()),
                ('aro_end', models.IntegerField()),
                ('evalue', models.FloatField()),
                ('bitscore', models.FloatField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resistome.Sample')),
            ],
        ),
    ]
