# Generated by Django 2.1.2 on 2018-11-22 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0011_contigtoblastresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiToTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gi', models.BigIntegerField()),
                ('taxon', models.IntegerField()),
            ],
        ),
    ]
