# Generated by Django 2.1.2 on 2018-11-22 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0013_taxondb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxondb',
            name='taxon_name',
            field=models.CharField(max_length=300),
        ),
    ]
