# Generated by Django 2.1.2 on 2018-11-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resistome', '0014_auto_20181122_1548'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContigToBlast2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contig_name', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=50)),
                ('pident', models.FloatField()),
                ('alignment_length', models.IntegerField()),
                ('mismatch', models.IntegerField()),
                ('gap_open', models.IntegerField()),
                ('contig_start', models.IntegerField()),
                ('contig_end', models.IntegerField()),
                ('subject_start', models.IntegerField()),
                ('subject_end', models.IntegerField()),
                ('evalue', models.FloatField()),
                ('bitsocre', models.FloatField()),
                ('contig_coverage', models.FloatField()),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resistome.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='SequenceIdToTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('taxon_id', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sequenceidtotaxon',
            unique_together={('subject', 'taxon_id')},
        ),
    ]
